### ISSUE TITLE
chord doesn't get bound on deferred packages

### ISSUE THREAD

**Issue by edvorg** [waymondo/use-package-chords#10]
minimal example

``` elisp
(use-package ace-window
  :chords ((";o" . ace-window))
  :bind ("C-x o" . ace-window))
```

chord `;o` doesn't work until I load ace-window somehow (by `C-x o` key binding or by `require`)

**Comment by waymondo** [comment]
Your example works me if I drop that in my `.emacs.d`. This was a known issue but it was addressed here: https://github.com/waymondo/use-package-chords/commit/b7de6b2a1270d37a1aca3bd8f29f67ec578527d7.  What versions of `use-package` and `use-package-chords` are you using? If they are outdated, try updating them both and let me know if it works.

**Comment by edvorg** [comment]
Seems like it was my local issue.. use-package were called using eval, macroexpand-all before eval helped to fix this
