### ISSUE TITLE
M-x describe-personal-keybindings breaks for global-map keychords

### ISSUE THREAD

**Issue by kaushalmodi** [waymondo/use-package-chords#3]
Hi,

If I have a `use-package` form like below in my config

```
(use-package eww
  :chords (("-=" . eww)))
```

that breaks M-x describe-personal-bindings because the `nil` keymap var is passed as (apparently) interned `keymap`. Running the above command gives error that `keymap` map is not found.

To fix that I needed to do patch the `bind-chord` function as below:

```
(defun bind-chord (chord command &optional keymap)
  "Bind CHORD to COMMAND in KEYMAP (`global-map' if not passed)."

  (let ((key1 (logand 255 (aref chord 0)))
        (key2 (logand 255 (aref chord 1))))
    (if (eq key1 key2)
        (if keymap
            (bind-key (vector 'key-chord key1 key2) command keymap)
          (bind-key (vector 'key-chord key1 key2) command))
      (if keymap
          (progn
            (bind-key (vector 'key-chord key1 key2) command keymap)
            (bind-key (vector 'key-chord key2 key1) command keymap))
        (bind-key (vector 'key-chord key1 key2) command)
        (bind-key (vector 'key-chord key2 key1) command)))))
```

I am sure there must be a more elegant way to fix this. But can you confirm that you too see this issue and fix it?

Thanks.

**Comment by waymondo** [comment]
Ah, yes, I'm seeing this as well. I'm guessing there is a cleaner way to do this but I'm not aware of one off the top of my head. I will do some research and patch it soon.

**Comment by waymondo** [comment]
closing as @nandryshak found the source of the issue :clap:

**Comment by nandryshak** [comment]
Ehh, I think I may have jumped the gun. There's some talk in that `use-package` pull request about rewriting `bind-key` as a function, but for now, I think a better solution is to rewrite `bind-chord` as a macro: https://github.com/waymondo/use-package-chords/pull/4
