### ISSUE TITLE
Unexpected behaviour together with `:bind` keyword

### ISSUE THREAD

**Issue by bixuanzju** [waymondo/use-package-chords#5]
Say I have the following snippet

```
(use-package foo
  :chords ("jj" . bar)
  :bind ("C-c k" . baz))
```

This would expands to

```
(progn
  (unless
      (fboundp 'bar)
    (autoload
      (function bar)
      "foo" nil t))
  (unless
      (fboundp 'baz)
    (autoload
      (function baz)
      "foo" nil t))
  (eval-after-load 'foo
    '(progn
       (unless
           (fboundp 'bar)
         (autoload
           (function bar)
           "foo" nil t))
       (unless
           (fboundp 'baz)
         (autoload
           (function baz)
           "foo" nil t))
       (ignore
        (bind-chords
         ("jj" . bar)))))
  (ignore
   (bind-keys
    ("C-c k" . baz))))
```

As you can see, `bind-chords` is wrapped inside `eval-after-load`, which means unless I press `C-c k` to force load the package `foo`, pressing `jj` would not work. BTW, there are some redundant  `fboundp .. autoload ..` pattern around, is this normal?

**Comment by jethrokuan** [comment]
+1 facing the same issue

**Comment by waymondo** [comment]
Thanks for noting this. I'm seeing this too when you combine `:bind` and `:chords` keywords.

I'm not sure what causes this without digging deep - `bind-chords` is just a thin layer on top of `bind-key` - but it looks like `:bind` is going to go through a re-working phase in `use-package` so I'll take another look at this once the dust settles over there unless someone else feels inspired to tackle it.

related:
https://github.com/jwiegley/use-package/issues/226
https://github.com/jwiegley/use-package/issues/237

**Comment by jordonbiondo** [comment]
After running into this I started using my own `:chords` handler that uses the existing `:preface` handler instead of the `:bind` handler. It creates autoloads and runs `bind-chord` on init.

So doing 

```
(use-packge foobar-mode 
  :chords (("nn . foobar)))
```

is equivalent to doing

```
(use-package foobar-mode
  :init
  (autoload 'foobar "foobar-mode")
  (bind-chord "nn" 'foobar))
```

It doesn't support `:map` but it would be trivial to add, you can see it here:

https://github.com/jordonbiondo/.emacs.d/blob/master/jordon/jordon-use-package-chords.el

**Comment by waymondo** [comment]
Thanks for sharing this, clever workaround. Verified it works so I'm going to snag this.

**Comment by jordonbiondo** [comment]
Cool beans. Note that you did lose :map functionality with that commit
