### ISSUE TITLE
Autoloading stopped working after last commit

### ISSUE THREAD

**Issue by kaushalmodi** [waymondo/use-package-chords#9]
Hi,

I noticed that autoloading based on `:chords` bindings broke after the last commit ( https://github.com/waymondo/use-package-chords/commit/14014ca8a6ec766bcf06cb828134f65cc3c439a0 ).

If I evaluate the use-package-chords.el from the second to last commit ( https://github.com/waymondo/use-package-chords/commit/cbf623c867f911732077b026692f9312401791ad ), autoloding starts working once again.

**Comment by kaushalmodi** [comment]
Here's a very simple example:

``` el
(use-package eww
  :chords (("-=" . eww)))
```

Ensure that `eww` is not force required. After you start emacs, `(featurep 'eww)` should return nil.
When you hit the `-=` chord, eww should get autoloaded. But it does not after the last commit.

**Comment by waymondo** [comment]
Ah nuts, I will try and check this out later today. Thanks for pointing out.

**Comment by waymondo** [comment]
Sorry for the delay. What version of `use-package` are you using?

**Comment by kaushalmodi** [comment]
I am using the latest version from Melpa: 20160226.1618

Thanks for looking into this. Are you unable to replicate the issue?

**Comment by waymondo** [comment]
I'm not able to reproduce the simple example above. Once the `use-package` block is evaluated, `(featurep 'eww)` is not nil. When I run:

```
(macroexpand
 '(use-package eww
    :chords ("-=" . eww)))
```

I get:

```
(if
    (not
     (require 'eww nil 'noerror))
    (ignore
     (message
      (format "Cannot load %s" 'eww)))
  (unless
      (fboundp 'eww)
    (autoload #'eww "eww" nil t))
  (ignore
   (progn
     (bind-key
      (vector 'key-chord 45 61)
      'eww nil)
     (bind-key
      (vector 'key-chord 61 45)
      'eww nil))))
```

Which looks correct to me.
- It requires the package.
- Granted there are no package requiring errors, it sees if `eww` is defined. If not, it defines an autoload for it.
- Then it binds `eww` to the appropriate `key-chord` vectors.

Is there something I'm missing?

**Comment by kaushalmodi** [comment]
Hi,

Sorry, I had given an incorrect example.

Here's the example, modified, that shows the problem.

## Example snippet

``` el
(use-package eww
  :commands (eww) ; missed this line earlier
  :chords ("-=" . eww))
```

With commit ( https://github.com/waymondo/use-package-chords/commit/14014ca8a6ec766bcf06cb828134f65cc3c439a0 ), on applying `pp-macroexpand-last-sexp` to above, I get:

``` el
(progn
  (unless
      (fboundp 'eww)
    (autoload #'eww "eww" nil t))
  (eval-after-load 'eww
    '(progn
       (unless
           (fboundp 'eww)
         (autoload #'eww "eww" nil t))
       (ignore
        (bind-chords
         ("-=" . eww))))))
```

Whereas with the working commit for me ( https://github.com/waymondo/use-package-chords/commit/cbf623c867f911732077b026692f9312401791ad ), the same gives:

``` el
(progn
  (unless
      (fboundp 'eww)
    (autoload #'eww "eww" nil t))
  (eval-after-load 'eww
    '(eval-and-compile
       (progn
         (autoload 'eww "eww")
         (bind-chord "-=" 'eww)))))
```

The main difference I see is that the working case has `eval-and-compile` while the non-working case does not. I don't understand the implication of that, but the effect is that the `"-="` key chord does not autoload eww when using the latest commit.

**Comment by waymondo** [comment]
Ok, this should be resolved in the commit above. Tracking this down was tricky but here's my take on what the issue was:

When you add `eww` to the `:commands` keyword, it pushes the autoloading of that function into the `:defer` block, which gets processed before the `:chords` command is processed, so the chord definition didn't get wired correctly. This also caused an issue if you defined a `:bind` and `:chord` block for autoloaded commands on deferred packages. By wrapping the chord binding in the `:preface` keyword, this ensures that the bindings you add go through the `eval-and-compile` procedure, even if the package and autoloading is deferred.

Let me know if you notice any other issues.

**Comment by kaushalmodi** [comment]
Thanks for fixing this!
